### ISSUE TITLE
app.py location

### ISSUE THREAD

**Issue by JustBerry** [JustBerry/SPIArticleAnalyzer#5]
https://wikitech.wikimedia.org/wiki/Help:Tool_Labs/My_first_Flask_OAuth_tool suggests that app.py be in $HOME/www/python/src. 

@stwalkerster Considering revision of proposed path change from pull request https://github.com/stwalkerster/SPIArticleAnalyzer/commit/7b492707e6d4d1b16b5359ff913c19c37a80b0a4#diff-688ea0d5b24d57ca1aa4b13b778e74bf.

**Comment by JustBerry** [comment]
This may be a helpful model: https://phabricator.wikimedia.org/source/tool-my-first-flask-oauth-tool/.

**Comment by stwalkerster** [comment]
@JustBerry I don't see what environment-specific file paths have to do with the codebase on a basic level - that's a deployment problem not a development problem.

Regarding the file paths on tool labs, you'll notice that [I did put app.py in $HOME/www/python/src](http://enwp.org/symlink), and that the repo you linked does have the app.py in a non-environment-specific folder, and the repository is cloned to the correct folder for the environment, very similarly to what I configured when I SSH'd in the other day for you.

I'm not sure what this issue is actually for...?
